# Generated by Django 5.2.6 on 2025-09-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allStudet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('pw', models.CharField(max_length=4)),
            ],
        ),
    ]
